name: tfsec-pr-commenter
on:
  pull_request:
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: Enable debugging output
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
      - name: Enable all action logging
        env:
          ACTIONS_RUNNER_DEBUG: 1
      - name: validation
        run: env | grep PAT
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          tfsec_args: --soft-fail
          github_token: ${{ github.token }}
          working_directory: ''
